services:
  api:
    build: 
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/app_db
      - RUST_BACKTRACE=1
    depends_on:
      - db
    volumes:
      - ./api:/app
      - cargo_cache:/usr/local/cargo/registry
    stdin_open: true
    tty: true

  db:
    build: ./db
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
  cargo_cache:
